import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import AppShell from "../../components/AppShell";
import { DecisionBadge, ErrorState, LoadingState, PageHeader, RiskBadge } from "../../components/UI";
import { api, Transaction } from "../../services/api";

export default function TransactionDetails() { const router = useRouter(); const [item, setItem] = useState<Transaction | null>(null); const [error, setError] = useState(""); useEffect(() => { if (typeof router.query.id === "string") api.transaction(router.query.id).then(setItem).catch((err) => setError(err.message)); }, [router.query.id]); return <AppShell><section className="page narrow-page"><Link className="back-link" href="/transactions">← Back to transactions</Link>{error ? <ErrorState message={error} /> : !item ? <LoadingState /> : <><PageHeader eyebrow={`Transaction / ${item.id.slice(0, 12)}`} title="Transaction details" description={new Date(item.occurred_at).toLocaleString()} action={<DecisionBadge value={item.analysis?.decision} />} /><div className="detail-hero"><div><span className="eyebrow">Risk score</span><strong>{item.analysis?.risk_score.toFixed(1) || "—"}</strong><span>/ 100</span></div><RiskBadge value={item.analysis?.risk_level} /></div><div className="detail-grid"><div className="panel"><span className="eyebrow">Signal breakdown</span><h3>Analysis</h3>{item.analysis && <div className="signal-list"><Signal label="Fraud probability" value={item.analysis.fraud_probability} /><Signal label="Anomaly score" value={item.analysis.anomaly_score} /></div>}</div><div className="panel"><span className="eyebrow">Explainability</span><h3>Decision reasons</h3><ul className="reason-list">{(item.analysis?.reasons || []).map((reason) => <li key={reason}>{reason}</li>)}</ul></div></div></>}</section></AppShell>; }
function Signal({ label, value }: { label: string; value: number }) { return <div className="signal"><div><span>{label}</span><strong>{(value * 100).toFixed(1)}%</strong></div><div className="signal-bar"><i style={{ width: `${Math.min(100, value * 100)}%` }} /></div></div>; }
