import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import AppShell from "../../components/AppShell";
import { ErrorState, LoadingState, NotConnected, PageHeader, Panel, RiskBadge, DecisionBadge, EvidenceBar } from "../../components/UI";
import { api, Transaction } from "../../services/api";

export default function Transactions() {
  const [items, setItems] = useState<Transaction[] | null>(null);
  const [query, setQuery] = useState("");
  const [risk, setRisk] = useState("ALL");
  const [error, setError] = useState("");
  useEffect(() => { api.transactions(200).then((data) => setItems(data.items)).catch((err) => setError(err instanceof Error ? err.message : "Transaction service unavailable")); }, []);
  const filtered = useMemo(() => items?.filter((item) => { const matchesQuery = !query || item.id.toLowerCase().includes(query.toLowerCase()) || item.currency.toLowerCase().includes(query.toLowerCase()); const matchesRisk = risk === "ALL" || item.analysis?.risk_level === risk; return matchesQuery && matchesRisk; }), [items, query, risk]);
  return <AppShell><section className="page"><PageHeader eyebrow="Evidence / transaction stream" title="Transaction intelligence" description="Search analyzed events, inspect their evidence, and drill into related entities." />{error ? <ErrorState message={error} /> : !items ? <LoadingState /> : <div className="workspace-grid"><Panel className="wide" title={`${filtered?.length || 0} transactions in view`} eyebrow="Search and filter"><div className="filter-bar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search transaction ID or currency" aria-label="Search transactions" /><select value={risk} onChange={(event) => setRisk(event.target.value)} aria-label="Filter by risk"><option value="ALL">All risk</option><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option></select><button className="ghost-button" onClick={() => { setQuery(""); setRisk("ALL"); }}>Reset filters</button></div>{filtered?.length ? <div className="table-wrap"><table><thead><tr><th>Transaction</th><th>Occurred</th><th>Amount</th><th>Probability</th><th>Anomaly</th><th>Decision</th><th /></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><span className="mono">{item.id.slice(0, 14)}</span><small>{item.status}</small></td><td>{new Date(item.occurred_at).toLocaleString()}</td><td className="amount">{item.currency} {Number(item.amount).toFixed(2)}</td><td>{item.analysis ? `${(item.analysis.fraud_probability * 100).toFixed(1)}%` : "Not available"}</td><td>{item.analysis ? `${(item.analysis.anomaly_score * 100).toFixed(1)}%` : "Not available"}</td><td><DecisionBadge value={item.analysis?.decision} /></td><td><Link className="text-link" href={`/transactions/${item.id}`}>Inspect ↗</Link></td></tr>)}</tbody></table></div> : <NotConnected detail="No matching transactions were returned by the backend." />}</Panel><Panel title="Evidence lens" eyebrow="Selected transaction"><NotConnected detail="Select a transaction to load behavior, network, rules, explanation, and related entities." /><div className="evidence-list"><EvidenceBar label="Fraud probability" /><EvidenceBar label="Anomaly score" tone="amber" /><EvidenceBar label="Behavioral deviation" tone="red" /><EvidenceBar label="Network risk" tone="green" /></div></Panel></div>}</section></AppShell>;
}
