import { useEffect, useState } from "react";
import AppShell from "../components/AppShell";
import { ErrorState, LoadingState, NotConnected, PageHeader, Panel } from "../components/UI";
import { AdminUser, api, AuditLog, DetectionPolicy, ManagedModel } from "../services/api";

export default function Admin() {
  const [profile, setProfile] = useState<{ id: string; email: string; display_name: string | null; role: string } | null>(null);
  const [users, setUsers] = useState<AdminUser[] | null>(null); const [models, setModels] = useState<ManagedModel[] | null>(null); const [policy, setPolicy] = useState<DetectionPolicy | null>(null); const [logs, setLogs] = useState<AuditLog[] | null>(null); const [error, setError] = useState("");
  const load = () => { api.adminProfile().then(setProfile).catch((err) => setError(err instanceof Error ? err.message : "Administration service unavailable")); api.adminUsers().then((data) => setUsers(data.items)).catch(() => setUsers([])); api.adminModels().then(setModels).catch(() => setModels([])); api.detectionPolicy("risk-policy").then(setPolicy).catch(() => setPolicy(null)); api.auditLogs().then((data) => setLogs(data.items)).catch(() => setLogs([])); };
  useEffect(() => { load(); }, []);
  if (error) return <AppShell><section className="page"><ErrorState message={error} /></section></AppShell>;
  if (!profile) return <AppShell><section className="page"><LoadingState /></section></AppShell>;
  return <AppShell><section className="page"><PageHeader eyebrow="Control plane / governed access" title="System administration" description="Manage identities, roles, model deployment, detection policies, and audit evidence through backend-enforced permissions." /><div className="workspace-grid"><Panel title="Authenticated operator" eyebrow="Current session"><div className="identity-avatar">{(profile.display_name || profile.email).slice(0, 1).toUpperCase()}</div><h3>{profile.display_name || "Administrator"}</h3><p className="muted">{profile.email}</p><span className="role-chip">{profile.role} access</span></Panel><PolicyPanel policy={policy} onSaved={load} /></div><div className="workspace-grid"><Panel title="Users and roles" eyebrow="Identity administration">{users?.length ? <div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td>{user.email}<small>{user.display_name}</small></td><td><select value={user.role} onChange={(event) => api.updateUserRole(user.id, event.target.value as "ADMIN" | "INVESTIGATOR" | "ANALYST").then(load).catch((err) => setError(err.message))}><option>ADMIN</option><option>INVESTIGATOR</option><option>ANALYST</option></select></td><td>{user.is_active ? "Active" : "Inactive"}</td></tr>)}</tbody></table></div> : <NotConnected detail="User and role data is not available." />}</Panel><Panel title="Model versions" eyebrow="Deployment control">{models?.length ? <div className="metric-table">{models.map((model) => <div key={model.id}><span>{model.model_name} v{model.version}</span><strong><button className="secondary-button" disabled={model.is_active} onClick={() => api.deployModel(model.id).then(load).catch((err) => setError(err.message))}>{model.is_active ? "Active" : "Deploy"}</button></strong></div>)}</div> : <NotConnected detail="No model versions are registered." />}</Panel></div><Panel title="Audit logs" eyebrow="Immutable activity trail">{logs?.length ? <div className="table-wrap"><table><thead><tr><th>Event</th><th>Resource</th><th>Actor</th><th>Created</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id}><td>{log.event_type}</td><td>{log.resource_type} {log.resource_id || ""}</td><td className="mono">{log.actor_user_id || "System"}</td><td>{new Date(log.created_at).toLocaleString()}</td></tr>)}</tbody></table></div> : <NotConnected detail="No audit events are stored." />}</Panel></section></AppShell>;
}

function PolicyPanel({ policy, onSaved }: { policy: DetectionPolicy | null; onSaved: () => void }) {
  const [value, setValue] = useState(JSON.stringify(policy?.configuration || {}, null, 2)); const [error, setError] = useState("");
  useEffect(() => setValue(JSON.stringify(policy?.configuration || {}, null, 2)), [policy]);
  return <Panel title="Detection policy" eyebrow="Policy configuration">{error && <ErrorState message={error} />}<textarea value={value} onChange={(event) => setValue(event.target.value)} rows={6} aria-label="Detection policy JSON" /><button className="primary-button" style={{ marginTop: "12px" }} onClick={() => { try { void api.updateDetectionPolicy("risk-policy", JSON.parse(value)).then(onSaved).catch((err) => setError(err.message)); } catch { setError("Policy must be valid JSON"); } }}>Save policy</button></Panel>;
}