import { useEffect, useState } from "react";
import AppShell from "../components/AppShell";
import { EmptyState, ErrorState, LoadingState, PageHeader, RiskBadge, StatCard } from "../components/UI";
import { api, DashboardStatistics, Transaction } from "../services/api";
import Link from "next/link";

export default function Dashboard() {
  const [stats, setStats] = useState<DashboardStatistics | null>(null); const [transactions, setTransactions] = useState<Transaction[]>([]); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.statistics(), api.transactions(5)]).then(([summary, history]) => { setStats(summary); setTransactions(history.items); }).catch((err) => setError(err instanceof Error ? err.message : "Unable to load dashboard")); }, []);
  return <AppShell><section className="page"><PageHeader eyebrow="Overview / live" title="Good morning, analyst." description="A clear view of your transaction risk posture." action={<Link className="primary-button compact" href="/simulator">Run simulation <span>↗</span></Link>} />{error ? <ErrorState message={error} /> : !stats ? <LoadingState /> : <><div className="stat-grid"><StatCard label="Transactions monitored" value={stats.total_transactions.toLocaleString()} /><StatCard label="Active alerts" value={stats.total_alerts.toLocaleString()} accent="lime" /><StatCard label="High risk" value={stats.high_risk_transactions.toLocaleString()} accent="coral" /><StatCard label="Blocked" value={stats.blocked_transactions.toLocaleString()} /></div><div className="content-grid"><div className="panel wide-panel"><div className="panel-heading"><div><span className="eyebrow">Latest activity</span><h3>Recent transactions</h3></div><Link href="/transactions">View all ↗</Link></div>{transactions.length ? <TransactionTable items={transactions} /> : <EmptyState title="No transactions yet" detail="Run a simulation or send a transaction to begin." />}</div><div className="panel posture-panel"><span className="eyebrow">Decision posture</span><h3>Current mix</h3><div className="mix-row"><span>Approved</span><strong>{stats.approved_transactions}</strong></div><div className="mix-bar"><i style={{ width: `${stats.total_transactions ? stats.approved_transactions / stats.total_transactions * 100 : 0}%` }} /></div><div className="mix-row"><span>Review queue</span><strong>{stats.review_transactions}</strong></div><div className="mix-row"><span>Blocked</span><strong>{stats.blocked_transactions}</strong></div><Link className="text-link" href="/analytics">Explore analytics ↗</Link></div></div></>}</section></AppShell>;
}
function TransactionTable({ items }: { items: Transaction[] }) { return <div className="table-wrap"><table><thead><tr><th>Transaction</th><th>Amount</th><th>Risk</th><th>Decision</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><span className="mono">{item.id.slice(0, 8)}</span><small>{new Date(item.created_at).toLocaleString()}</small></td><td className="amount">{item.currency} {Number(item.amount).toFixed(2)}</td><td><RiskBadge value={item.analysis?.risk_level} /></td><td>{item.analysis?.decision || "PENDING"}</td><td><Link className="row-link" href={`/transactions/${item.id}`}>↗</Link></td></tr>)}</tbody></table></div>;
}
