import Link from "next/link";
import { useEffect, useState } from "react";
import AppShell from "../components/AppShell";
import { ErrorState, LoadingState, MetricCard, NotConnected, PageHeader, Panel, RiskBadge, DecisionBadge } from "../components/UI";
import { api, DashboardStatistics, Transaction } from "../services/api";

export default function Dashboard() {
  const [stats, setStats] = useState<DashboardStatistics | null>(null);
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.statistics(), api.transactions(20)]).then(([summary, history]) => { setStats(summary); setTransactions(history.items); }).catch((err) => setError(err instanceof Error ? err.message : "Command center data unavailable")); }, []);
  return <AppShell><section className="page"><PageHeader eyebrow="Command center / live posture" title="Decision operations" description="A grounded view of the transaction stream, current risk distribution, and operational attention." action={<Link className="primary-button" href="/transactions">Inspect stream <span>↗</span></Link>} />
    {error ? <ErrorState message={error} /> : !stats ? <LoadingState /> : <><div className="metric-grid"><MetricCard label="Transaction volume" value="Not available" detail="Monetary aggregation not exposed" /><MetricCard label="Transactions analyzed" value={stats.total_transactions.toLocaleString()} tone="cyan" /><MetricCard label="Block rate" value={`${stats.fraud_rate.toFixed(1)}%`} detail="Backend blocked / total" tone="red" /><MetricCard label="Exposure prevented" value="Not available" detail="Requires outcome contract" /><MetricCard label="Active investigations" value="Not available" detail="Cases endpoint pending" tone="amber" /><MetricCard label="Critical alerts" value={stats.total_alerts.toLocaleString()} detail="Medium/high alert count" tone="red" /></div><div className="dashboard-grid"><Panel title="Fraud trend" eyebrow="Historical time series"><div className="chart-placeholder">Trend series requires analytics contract</div></Panel><Panel title="Risk distribution" eyebrow="Current observed stream"><RiskDistribution distribution={stats.risk_distribution} /></Panel></div><div className="dashboard-grid"><Panel title="Live detection feed" eyebrow="Latest analyzed transactions" action={<Link className="panel-link" href="/transactions">View all</Link>}>{transactions.length ? <div className="feed-list">{transactions.slice(0, 7).map((item) => <Link className="feed-row" href={`/transactions/${item.id}`} key={item.id}><span className={`feed-marker ${item.analysis?.risk_level?.toLowerCase() || ""}`} /><span className="feed-time">{new Date(item.created_at).toLocaleTimeString()}</span><span className="feed-reason">{item.analysis?.reasons?.[0] || "No explanation available"}</span><RiskBadge value={item.analysis?.risk_level} /></Link>)}</div> : <NotConnected detail="No transactions have been returned by the backend." />}</Panel><Panel title="Current attack activity" eyebrow="Campaign monitor"><NotConnected detail="Attack activity requires a campaign and network analytics contract." /></Panel></div><div className="dashboard-grid"><Panel title="Top risky merchants" eyebrow="Entity intelligence"><NotConnected detail="Merchant risk rankings are not available from the current backend." /></Panel><Panel title="Top risky devices" eyebrow="Entity intelligence"><NotConnected detail="Global device intelligence is not available from the current backend." /></Panel><Panel title="Model health" eyebrow="Production telemetry"><NotConnected detail="Model telemetry must be supplied by the model monitoring service." /></Panel></div></>}
  </section></AppShell>;
}

function RiskDistribution({ distribution }: { distribution: Record<string, number> }) { const max = Math.max(1, ...Object.values(distribution)); return <div className="risk-bars">{Object.entries(distribution).map(([level, count]) => <div className="risk-row" key={level}><span>{level}</span><div className="risk-track"><i className={level.toLowerCase()} style={{ width: `${count / max * 100}%` }} /></div><strong>{count}</strong></div>)}</div>; }
