import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/router";

import { api } from "../services/api";

export default function Register() {
  const router = useRouter(); const [form, setForm] = useState({ display_name: "", email: "", password: "" }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const result = await api.register(form); localStorage.setItem("fraudguard_token", result.access_token); await router.push("/dashboard"); } catch (err) { setError(err instanceof Error ? err.message : "Registration failed"); } finally { setBusy(false); } }
  return <div className="auth-page"><div className="auth-aside"><Link className="brand" href="/"><span className="brand-mark">X</span><span>FRAUD<span>GUARD</span><b> X</b></span></Link><div className="auth-statement"><span className="eyebrow">Operator provisioning / 03</span><h1>Build a<br /><em>clear case.</em></h1><p>Start a governed workspace for fraud intelligence and investigation.</p></div><div className="auth-aside-foot">PRIVATE INSTANCE<br />AUDITABLE BY DEFAULT</div></div><main className="auth-form-wrap"><div className="auth-form"><div className="eyebrow">Provision access</div><h2>Create an operator workspace</h2><p className="form-intro">Set up your secure fraud operations account.</p><form onSubmit={submit}><label>Your name<input required value={form.display_name} onChange={(event) => setForm({ ...form, display_name: event.target.value })} placeholder="Alex Morgan" /></label><label>Email address<input type="email" required value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="you@company.com" /></label><label>Password<input type="password" minLength={8} required value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="At least 8 characters" /></label>{error && <div className="form-error">{error}</div>}<button className="primary-button" disabled={busy}>{busy ? "Provisioning..." : "Create workspace"}<span>↗</span></button></form><p className="form-switch">Already have access? <Link href="/login">Enter console</Link></p></div></main></div>;
}
