import { FormEvent, useState } from "react";
import AppShell from "../components/AppShell";
import { DecisionBadge, ErrorState, NotConnected, PageHeader, Panel, RiskBadge } from "../components/UI";
import { api, AttackSimulation } from "../services/api";

const scenarios = [["normal", "Baseline activity", "A normal sequence for comparison."], ["account_takeover", "Account takeover", "New device, location, and amount shift."], ["card_testing", "Card testing", "Rapid low-value authorization probes."], ["velocity", "Velocity burst", "High-frequency payment activity."], ["impossible_travel", "Impossible travel", "Rapid movement between distant locations."], ["device_takeover", "Device takeover", "Trusted account on a replacement device."], ["fraud_ring", "Coordinated ring", "Multi-device activity around a high-risk merchant."]] as const;

export default function Simulator() {
  const [scenario, setScenario] = useState("account_takeover"); const [result, setResult] = useState<AttackSimulation | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { setResult(await api.attackSimulate({ attack_type: scenario, currency: "INR", base_location: "Bengaluru", base_amount: 1200 })); } catch (err) { setError(err instanceof Error ? err.message : "Simulator service unavailable"); } finally { setBusy(false); } }
  return <AppShell><section className="page"><PageHeader eyebrow="Red team / controlled replay" title="Attack simulator" description="Run labeled attack scenarios through the detection pipeline without presenting synthetic outcomes as production statistics." /><div className="workspace-grid"><Panel title="Scenario builder" eyebrow="Choose a replay"><form onSubmit={submit}><div className="scenario-grid">{scenarios.map(([value, label, detail]) => <label className={`scenario-option ${scenario === value ? "selected" : ""}`} key={value}><input type="radio" name="scenario" value={value} checked={scenario === value} onChange={(event) => setScenario(event.target.value)} /><span><strong>{label}</strong><small>{detail}</small></span></label>)}</div>{error && <ErrorState message={error} />}<button className="primary-button" disabled={busy}>{busy ? "Running labeled replay..." : "Launch scenario"}<span>↗</span></button></form></Panel>{result ? <SimulationReport result={result} /> : <Panel className="result-console" title="Simulation output" eyebrow="Awaiting replay"><NotConnected detail="A scenario run will return event-level detections, peak risk, and the labeled timeline here." /></Panel>}</div></section></AppShell>;
}

function SimulationReport({ result }: { result: AttackSimulation }) { return <Panel className="result-console" title="Simulation output" eyebrow={`${result.attack_type} / labeled replay`}><div className="detail-hero"><div><span className="eyebrow">Peak risk</span><strong>{result.peak_risk_score.toFixed(0)}</strong><span>/ 100</span></div><DecisionBadge value={result.detected ? "BLOCK" : "APPROVE"} /></div><div className="metric-grid"><div className="metric-card"><div className="metric-label">Generated</div><strong>{result.transactions_generated}</strong></div><div className="metric-card"><div className="metric-label">Detected</div><strong>{result.detected_transactions}</strong></div><div className="metric-card"><div className="metric-label">Detection rate</div><strong>{result.detection_rate.toFixed(1)}%</strong></div></div><div className="timeline-list">{result.transactions.map((item, index) => <div className="timeline-row" key={item.id}><span className="timeline-time">T+{index * 30}s</span><i className="timeline-dot" /><span className="timeline-copy"><strong>{item.currency} {Number(item.amount).toLocaleString()}</strong><small>{item.analysis?.reasons?.[0] || "No explanation returned"}</small></span><RiskBadge value={item.analysis?.risk_level} /></div>)}</div></Panel>; }
